### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [3]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - torch.linespace

In [7]:
# Example 1 - 可對選定範內的數字進行切分，相當於N分位數
torch.linspace(10, 100, steps=10)

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [8]:
# Example 2 - 可以選定倒退 ex end=負數
torch.linspace(10, end=-100, steps=10)

tensor([  10.0000,   -2.2222,  -14.4444,  -26.6667,  -38.8889,  -51.1111,
         -63.3333,  -75.5556,  -87.7778, -100.0000])

### Function 2 - torch.ones

In [12]:
# Example 1 - give the shape and return the full one tensor
torch.ones(2)

tensor([1., 1.])

In [14]:
# Example 2
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Function 3 - torch.as_tensor

In [22]:
# Example 1 - transport numpy to tensor, it can set the dtype and device locate
a = np.array([1,2,4])
torch.as_tensor(a, dtype=torch.float16, device = 'cuda')

tensor([1., 2., 4.], device='cuda:0', dtype=torch.float16)

### Function 4 - torch.flatten

In [25]:
# Example 1 - flatten tensor to the 1d tensor
a = torch.ones(2,4,3)
torch.flatten(a)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])